---
layout: cv
title: Sophie Miller's CV
---
# Sophie Miller
Business Analyst, Marketer, Fast Learner

<div>
<a href="mil20014@byui.edu">mil20014@byui.edu</a>
</div>


## Currently

Developing proficiency in analysis at BYU-Idaho. Fascinated by the intersection of analytics and storytelling; where accurate data meets skillful presentation. 

### Specialized in

Database Management: MySQL, relational database design
Data Processing & Analysis: SQL queries, Power BI, RStudio
Programming: Python (data visualization with Let’s Plot), Visual Studio Code
Process Improvement: Report generation, workflow optimization
Excel Expertise: Advanced formulas, macros, automation, data visualization


### Education and Experience

**Brigham Young University - Idaho**
Full-Time Student | Rexburg, ID *September 2020 - Present*
Developed and optimized relational databases with MySQL
Applied data visualization techniques using Power BI and RStudio for class projects
Designed an invoice tracking system in Excel with macro automation for email invoicing
Created reports with Python and SQL in Visual Studio Code


**Brigham Young University - Idaho**
Teacher's Assistant | Rexburg, ID *January 2025 - Present*
Reviewed and graded Excel-based assignments, reinforcing attention to detail and data
accuracy

**Integrated Business Core - "Gelly" Jar Candles**
Chief Operating Officer | Rexburg, ID *April 2024 - July 2024*
Led operations and presented business strategy to investors, securing startup funding
Spearheaded materials acquisition and inventory tracking using Excel, ensuring audit
compliance
Implemented data-driven decision-making processes to enhance operational efficiency

**Idahoan Foods**
Marketing Intern | Idaho Falls, ID *April 2022 - July 2022*
Created informational reports utilizing Adobe Illustrator
Developed an infographic video on local mountain ranges to demonstrate familiarity with
design principles and Adobe Creative Cloud software


## Awards

`2021'
1st Place Winner 2021 *Pre-Professional Writing Conference*


### Volunteer Experience

**Church of Jesus Christ of Latter-Day Saints**
Volunteer Representative | Mesa, AZ *September 2022 - February 2024*
Strengthened communication, leadership, and collaboration skills through daily interactions
and service

**Get Connected - Brigham Young University Idaho**
Student Support Representative | Rexburg, ID *April 2021*
Organized and led service activities, assisting incoming students in acclimating to BYU-I
Assisted with event logistics and team coordination, showcasing leadership skills


<!-- ### Footer

Last updated: April 2025-->